version: '3.8'

services:
  api:
    build: .
    container_name: my-node-app
    ports:
      - "0.0.0.0:3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
